### PR TITLE
Delete cmi5_test_requirments.md and cmi5_test_procedures.md

### PR DESCRIPTION
**Pull request by thomasturrell**
Now that the CATAPULT testing framework has been released I believe that these requirements are no longer required.

### CODE REVIEW

**Comment by brianjmiller** [comment]
`cmi5_test_procedures.md` can go away too

**Comment by MrBillMcDonald** [comment]
Per the Dec 16th meeting discussions, we may need to keep these documents for historical purposes.

We will discuss with the Catapult team.

**Comment by brianjmiller** [comment]
I don't think there is a reason these need to stay. If for some reason they need to be accessed they can always be retrieved via the history of this repository itself.

`cmi5_test_requirements.md` should be superseded by https://github.com/adlnet/CATAPULT/blob/main/requirements/requirements.json

`cmi5_test_procedures.md` should be superseded by
https://github.com/adlnet/CATAPULT/blob/main/lts/procedure.md

**Comment by MrBillMcDonald** [comment]
Approved per Jan 13th Meeting.

**Pull request merged**
