### PR TITLE
Remove line feed escape sequences from samples

### PR DESCRIPTION
**Pull request by thomasturrell**
All of the other samples do not contain the line feed escape sequence and spacing in description. 

I have removed them in these three files to be consistent with the other samples.

As noted by @brianjmiller if this pull request was accepted it would make sense to change the file [simple-cmi5.xml](https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/v1/examples/simple-cmi5.xml#L9) in a separate pull request.

**Please note that the title, summary and commits for this pull request have been changed to reflect the discussion below.**

### CODE REVIEW

**Comment by thomasturrell** [comment]
It would be helpful if PR #713 was merged first.

**Comment by cawerkenthin** [comment]
Not sure about this.  My company used the extra characters and spacing to improve our cmi5 import so I found it valuable; we cannot expect content tools to always provide clean data.  On the other hand, I can see how it might confuse someone.

**Comment by thomasturrell** [comment]
I'm happy either way, if there is a consensus I'm willing to change it everywhere. 

It had never occurred to me to use newlines in the description, I can see how that would be useful.

My 2 cents would be it looks odd in the sample on the website:

Screenshot 2021-06-10 at 17 28 16

**Comment by brianjmiller** [comment]
The newlines are inherited from the course structure example which includes them, so to be technically correct they should stay or should be removed from the course structure examples. See https://github.com/AICC/CMI-5_Spec_Current/blob/quartz/v1/examples/simple-cmi5.xml#L9

IOW, an LMS that imports that file and uses the metadata therein to create Activity Definitions (which I think we consider a reasonable approach) needs to include the newlines because they were part of the original data. There is no way an LMS can sufficiently understand embedded data in that value. The spec does require the removal of leading and trailing whitespace from those elements.

**Comment by thomasturrell** [comment]
But everyone is ok with launchMethod being removed from the launch data?

On balance, I think all the JSON samples that use the XML course structure example should all contain the new lines, I can update them all so that they do.

Slightly off topic, I'm fine with whitespace and newlines in Activity Definitions but markup (HTML or other) causes headaches.

**Comment by cawerkenthin** [comment]
Please point to the location in the spec where /n is to be considered a line feed.  I am unable to find it.

**Comment by cawerkenthin** [comment]
Seriously, is /n universal across operating systems?  (android, windows, mac, etc)?  I just don't know....

**Comment by thomasturrell** [comment]
> Seriously, is /n universal across operating systems? (android, windows, mac, etc)? I just don't know....

I think you mean mean `\n` not `/n`. (Sorry for being pedantic) 

That’s a huge can of worms!

I am not authority on this but I would like to add my thoughts.

The answer is no, it is not universal. Unlike most other operating systems Windows uses `\r\n` but the context matters which makes the answer complicated.

Given the following:

Screenshot 2021-06-11 at 12 19 31

A browser (Windows or Mac) would literally display the `\n` and treat the eight consecutive spaces as one space. Therefore it would rendered thus:

Screenshot 2021-06-11 at 12 20 29

A markdown parser (depending on how they interpret Markdown) would render it like:

Screenshot 2021-06-11 at 12 21 12

Without any parsing a native Windows application would probably render it (note the \n is invisible):

Screenshot 2021-06-11 at 12 22 14

Without any parsing a native Android application would probably render it (note the leading whitespace on the second line):

Screenshot 2021-06-11 at 12 22 55

In any scenario I don't see a single instance where what was displayed is what was (probably) intended.

> IOW, an LMS that imports that file and uses the metadata therein to create Activity Definitions (which I think we consider a reasonable approach) needs to include the newlines because they were part of the original data. There is no way an LMS can sufficiently understand embedded data in that value.

An application that displays the name and description values is probably going to have to parse them before displaying them to ensure that the user sees something sensible for their context. For example if the description is going to be displayed in a web page all of the newlines could be substituted for `<br>`. 

If absolutely nothing else the values need sanitising to avoid HTML injections.

`
This course will introduce you into the basics of geology. This includes subjects such as plate tectonics, geological materials and the history of the Earth.<iframe src="https://www.example.com/evil"></iframe>
`

Personally I think it’s best if a system validates all activity definitions on input, I would prohibit all HTML and escape sequences.

**Comment by brianjmiller** [comment]
I'm still fundamentally opposed to changing this in the JSON **without** making the corresponding changes in the XML files. The original source of the string has a newline, which is properly encoded as `\n` in the JSON string derived straight from the value from that source location. The newline as a "newline" is universally (well that's a big word, but for the definition you are using here) understood, it is the behavior of how to handle that newline that is not universally handled and changes depending on the context. If the intended string was supposed to have `\r\n` then we'd need to handle that the same way and the original source would have to be changed to include the `\r` (carriage return).

Note I'm not saying this is good practice, and I'm not saying it will render naturally as I suspect the original author intended, but the `\n` is IMO correct based on the source material.

> If absolutely nothing else the values need sanitising to avoid HTML injections.

Only if intending to be rendered into an HTML document. We just can't know what the author intended or where it will be used. There are safe ways of injecting user provided data into HTML documents, developers should be taking care based on those practices with untrusted data rather than having something in this spec to handle it. (Also see https://github.com/adlnet/xAPI-Spec/issues/475 and the follow up.)

> Personally I think it’s best if a system validates all activity definitions on input, I would prohibit all HTML and escape sequences.

This is a giant can of worms, and while I appreciate the sentiment it is intended to convey, our best approach should be to leave the string handled as the underlying XML expects it to be handled and not push any validation on top of it. If an implementation wants to inspect the values therein there isn't really anything stopping them.

**Comment by thomasturrell** [comment]
> I'm still fundamentally opposed to changing this in the JSON without making the corresponding changes in the XML files

They are in different branches so it's technically impossible to make the changes at exactly the same time. I can however open the pull request for the other change and link it here. However, I don't want to do that until there is a consensus.

> the \n is IMO correct based on the source material.

I don't mind either way I just think the samples should be consistent, some use the `\n` some don't. More don't than do. I'm happy to open a pull request for the opposite (add the `\n` everywhere) or happy to drop this pull request all together.

For the record, I had no idea this would prove so controversial! Originally I was simply interested in clarifying the launch data in the samples (now moved to #717).

**Comment by thomasturrell** [comment]
Should be reviewed with #712

**Comment by thomasturrell** [comment]
Most (all?) XML parsers will drop the new lines and all multiple concurrent spaces will be treated as one space ([see demo](https://jsfiddle.net/jkh1z9L2/)).

**Comment by thomasturrell** [comment]
> Most (all?) XML parsers will drop the new lines and all multiple concurrent spaces will be treated as one space (see demo).

As pointed out by @gavbaa this is incorrect.

@gavbaa I would be very grateful if you could review this and associated pull requests and give your opinion.

My understanding of what you are saying is that:

```XML
<description>
  <langstring lang="en-US">
    This course will introduce you into the basics of geology. This includes subjects such as
    plate tectonics, geological materials and the history of the Earth.
  </langstring>
</description>
```

Should be parsed and then transformed into JSON as:

```JSON
 "description": 
  {
    "en-US": "This course will introduce you into the basics of geology. This includes subjects such as plate tectonics, geological materials and the history of the Earth."
  }
```

Is that correct?

**Comment by gavbaa** [comment]
`description` is a `textType` in the XSD.  Here's how that's defined:

```
  <xs:complexType name="textType">
    <xs:sequence>
      <xs:element name="langstring" maxOccurs="unbounded" minOccurs="1">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="lang" type="xs:language"/>
              <xs:attributeGroup ref="anyAttribute"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:group ref="anyElement"/>
    </xs:sequence>
    <xs:attributeGroup ref="anyAttribute"/>
  </xs:complexType>
```

Important to note: `langString` is an `xs:string`.  From the XSD spec: 

> for string the value of whiteSpace is preserve

This means at the XML parser level, whitespace should be preserved exactly as is.  Then, per cmi5 13.1:

> All leading/trailing whitespace MUST be removed by the LMS on import of the course structure for all of the data elements defined in this section.

You would trim the whitespace off the outside, but preserve it without collapsing on the inside.  Your most recent interpretation, by those rules, would be incorrect, as it's missing the internal whitespace representation.

**Comment by thomasturrell** [comment]
> You would trim the whitespace off the outside, but preserve it without collapsing on the inside. Your most recent interpretation, by those rules, would be incorrect, as it's missing the internal whitespace representation.

Understood. Thank you for your time on this, your input has been very useful and educational to me.

**Pull request closed without merging**
