### PR TITLE
editorial fixes - conceptual model

### PR DESCRIPTION
**Pull request by davidpesce**

### CODE REVIEW

**Comment by andyjohnson** [comment]
There are actual spec changes in here in the runtime, please revise.  We don't have an "exited" verb.  Something I did see though, because of this PR:  "which may contain one or more Assignable Units", this "may" should be a MUST, right?

**Comment by davidpesce** [comment]
I assumed these should match each other (coursestructure and runtime). This may be a discussion point. I'm around today and can set up a conference line to discuss.

**Comment by andyjohnson** [comment]
Not sure which isn't matching, but the differences I'm seeing are "exited" vs "terminated" (which wasn't worded very well to begin with, we mean a "terminated" statement right?) ,  "he LMS writes lauch data to the integrated LRS. " being taken out in this PR, and removal of the "one or more AU" language.  If you can revert the other two ("terminated" is good enough for now), I can merge the rest.  Thanks so much for all of these, @davidpesce

**Comment by davidpesce** [comment]
OK, this should be all set!

One thing I did just notice was that the synopsis should be an ordered list. Thoughts?

**Comment by andyjohnson** [comment]
I'd say leave it for now, just in case two steps are interchangeable and we have interoperability issues

**Pull request merged**
