### PR TITLE
Remove duplicate satisfied statement in JSON sample

### PR DESCRIPTION
**Pull request by thomasturrell**
Satisfied statement has a separate file, therefore this is an unnecessary duplicate.

### CODE REVIEW

**Comment by thomasturrell** [comment]
See the the JSON samples for [cmi5 allowed test question statements](http://aicc.github.io/CMI-5_Spec_Current/samples/scenarios/19-cmi5-allowed-test-questions/#satisfied-allowed-statement).

**Comment by cawerkenthin** [comment]
I don't believe these are duplicates.  One is sent by the AU as a "cmi5 allowed" statement.  The other is sent by the LMS as a "cmi5 defined" statement.  Note the use of the following in the LMS statement:
"category": [
        {
          "objectType": "Activity",
          "id": "https://w3id.org/xapi/cmi5/context/categories/cmi5"
        }
      ]

**Comment by thomasturrell** [comment]
There are three statements in the sample that have the verb https://w3id.org/xapi/adl/verbs/satisfied. 

Two of the statements have the same statement id (a26bfaa4-8f23-4d29-9d90-25cf346e5206).

Perhaps the correct thing to do is change one of the statements to have a different statement id?

**Comment by brianjmiller** [comment]
I think this is correct as is in the PR. The section being deleted is at the bottom of the terminated statement JSON block.
image

So even with this deleted the two satisfied statements will still be present since they are included via their own file.

**Comment by cawerkenthin** [comment]
👍

**Pull request merged**
