### PR TITLE
Update requirements for LMS.LaunchData

### PR DESCRIPTION
**Pull request by brianjmiller**
Remove the latter sentence because either:

1) It doesn't work with the concept of multiple session ids per registration, or
2) The LRS won't allow it to store two different document bodies for the given set of keys (activityId, agent, registration, and stateId).

Add that it can be an "update" because it will have to be (assuming the document hasn't been first deleted) when multiple sessions are in play.

### CODE REVIEW

**Comment by cawerkenthin** [comment]
:+1:

**Comment by MrBillMcDonald** [comment]
Brian, is there an issue associated with this request ?

**Comment by andyjohnson** [comment]
Per the 3/4/16 call, good to go, just move the Properties portion at the end of the section closer to the top for clarity.

**Comment by brianjmiller** [comment]
Edits have been made to satisfy comments from 03/04/2016 call.

**Pull request merged**
